apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: miniapp
type: Opaque
data:
  DB_PASSWORD: cGFzcw==


# pass
# Base64 Enconding: echo -n "pass" | base64
# Base64 Decoding: echo "cGFzcw==" | base64 --decode